<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareLibre [
<!ELEMENT softwareLibre (aplicaciones, licencias)>
<!ELEMENT version EMPTY>
<!ELEMENT licencia EMPTY>
<!ELEMENT aplicaciones (aplicacion)+>
<!ELEMENT licencias (licencia)+>
<!ELEMENT aplicacion (version)+>
<!ATTLIST aplicacion nombre CDATA #REQUIRED>
<!ATTLIST version id CDATA #REQUIRED>
<!ATTLIST version licencia CDATA #REQUIRED>
<!ATTLIST version fechaPubli CDATA #IMPLIED>
<!ATTLIST licencia app CDATA #REQUIRED>
]>
<softwareLibre>
    <aplicaciones>
            <aplicacion nombre="Inkscape">
                <version id="0.47" licencia="GPL v2" fechaPubli="17/08/2010" />
                <version id="0.48" licencia="GPL v2" fechaPubli="17/08/2010" />
                <version id="0.48.2" licencia="GPL v2" fechaPubli="14/08/2011" />
            </aplicacion>
            <aplicacion nombre="PostgreSQL">
                <version id="9.1.0" licencia="BSD2" fechaPubli="15/09/2011" />
                <version id="9.1.3" licencia="BSD2"/>
            </aplicacion>
    </aplicaciones>
            <licencias>
                <licencia app="GPL v2" />
                <licencia app="BSD2" />
                <licencia app="Apache v2" />
            </licencias>
</softwareLibre>