=== Jaime-asir/LDM/Jaime/Tareas/Tarea 2.5/docu4.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.w3schools.com"
    xmlns="https://www.w3schools.com"
    elementFormDefault="qualified">
  <xs:element name="matricula">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personal">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="dni"/>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="titulacion"/>
              <xs:element type="xs:string" name="curso_academico"/>
              <xs:element name="domicilios">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="domicilio" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="calle"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="tipo" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="pago">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="tipo_matricula"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jaime-asir/LDM/Jaime/Tareas/Tarea 2.5/docu4.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<matricula
    xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com/xml docu4.xsd">
<personal>
    <dni>99223366M</dni>
    <nombre>Juan Pardo Martín</nombre>
    <titulacion>Ingeniería Informática</titulacion>
    <curso_academico>1997/1998</curso_academico>
    <domicilios>
        <domicilio tipo="familiar">
            <calle>C/ Principal nº1</calle>
        </domicilio>
        <domicilio tipo="habitual">
            <calle>C/ Secundaria nº2</calle>
        </domicilio>
    </domicilios>
</personal>
<pago>
    <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
</pago>
</matricula>
